# Generated by Django 3.1.6 on 2021-02-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.JSONField()),
                ('operator', models.TextField(choices=[('min', 'Minimum'), ('max', 'Maximum')])),
                ('time', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.JSONField()),
                ('operator', models.TextField(choices=[('min', 'Minimum'), ('max', 'Maximum')])),
                ('severity', models.PositiveSmallIntegerField(verbose_name='Alert Severity (0 highest)')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='HostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('registration_key', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('name', models.TextField()),
                ('metric_type', models.TextField(choices=[('int', 'Integer'), ('float', 'Floating point'), ('array', 'List')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notification_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('teams', models.ManyToManyField(to='web.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(to='web.User'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField()),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.host')),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.metric')),
            ],
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['category', 'name'], name='web_metric_categor_9f4d16_idx'),
        ),
        migrations.AddField(
            model_name='hosttag',
            name='hosts',
            field=models.ManyToManyField(to='web.Host'),
        ),
        migrations.AddField(
            model_name='host',
            name='tags',
            field=models.ManyToManyField(to='web.HostTag'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='host_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.hosttag'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.metric'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.team'),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.user'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.alertrule'),
        ),
        migrations.AddField(
            model_name='alert',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.host'),
        ),
        migrations.AddField(
            model_name='alert',
            name='host_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.hosttag'),
        ),
        migrations.AddField(
            model_name='alert',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.metric'),
        ),
        migrations.AddField(
            model_name='alert',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.report'),
        ),
        migrations.AddField(
            model_name='alert',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.team'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='web_user_name_62cf3f_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='web_team_name_e9e7db_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['time'], name='web_report_time_d6a548_idx'),
        ),
        migrations.AddIndex(
            model_name='hosttag',
            index=models.Index(fields=['name'], name='web_hosttag_name_a5fc70_idx'),
        ),
        migrations.AddIndex(
            model_name='hosttag',
            index=models.Index(fields=['registration_key'], name='web_hosttag_registr_5cd255_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['guid'], name='web_host_guid_c24b38_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['time'], name='web_alert_time_5b7b97_idx'),
        ),
    ]
