# Generated by Django 3.1.6 on 2021-02-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('metric_type', models.CharField(choices=[('perc', 'Percent'), ('count', 'Count'), ('bits', 'Bits')], max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.JSONField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.host')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.metric')),
            ],
        ),
        migrations.CreateModel(
            name='HostTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_key', models.CharField(max_length=256)),
                ('hosts', models.ManyToManyField(to='web.Host')),
            ],
        ),
    ]
