# Generated by Django 3.1.6 on 2021-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosttag',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='web.Host'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, to='web.Team'),
        ),
    ]
